-- Run this once in the Supabase SQL Editor.
-- Add only the two household emails to allowed_users after creating the table.

create table public.allowed_users (
  email text primary key check (email = lower(trim(email)))
);

alter table public.allowed_users enable row level security;

create policy "members can read only their own allowlist row"
on public.allowed_users
for select
to authenticated
using (email = lower(coalesce((select auth.jwt() ->> 'email'), '')));

create table public.shopping_items (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) between 1 and 120),
  name_key text not null unique,
  done boolean not null default false,
  sort_order bigint generated by default as identity,
  created_at timestamptz not null default now()
);

alter table public.shopping_items enable row level security;

create or replace function public.is_shopping_list_member()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.allowed_users
    where email = lower(coalesce((select auth.jwt() ->> 'email'), ''))
  );
$$;

revoke all on function public.is_shopping_list_member() from public, anon;
grant execute on function public.is_shopping_list_member() to authenticated;

grant select on public.allowed_users to authenticated;
grant select, insert, update, delete on public.shopping_items to authenticated;

create policy "authorized household can read items"
on public.shopping_items
for select
to authenticated
using ((select public.is_shopping_list_member()));

create policy "authorized household can add items"
on public.shopping_items
for insert
to authenticated
with check ((select public.is_shopping_list_member()));

create policy "authorized household can update items"
on public.shopping_items
for update
to authenticated
using ((select public.is_shopping_list_member()))
with check ((select public.is_shopping_list_member()));

create policy "authorized household can delete items"
on public.shopping_items
for delete
to authenticated
using ((select public.is_shopping_list_member()));
